services:
  api-prod:
    image: ghcr.io/langbapt/cesizen-api:prod
    container_name: api-prod
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      NODE_ENV: production
      PORT: 3000
    networks:
      - web
      - internal-prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.api-prod.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-prod.priority=20"
      - "traefik.http.services.api-prod.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.api-prod-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api-prod.middlewares=secure-headers@file,api-prod-strip"
    depends_on:
      - postgres-prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backoffice-prod:
    image: ghcr.io/langbapt/cesizen-backoffice:prod
    container_name: backoffice-prod
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backoffice-prod.rule=PathPrefix(`/`)"
      - "traefik.http.routers.backoffice-prod.entrypoints=websecure"
      - "traefik.http.routers.backoffice-prod.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backoffice-prod.middlewares=secure-headers@file"
      - "traefik.http.routers.backoffice-prod.priority=1"
      - "traefik.http.services.backoffice-prod.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres-prod:
    image: postgres:16-alpine
    container_name: postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    networks:
      - internal-prod
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  web:
    external: true
  internal-prod:
    driver: bridge

volumes:
  pgdata-prod: